services:
  #web is a service name (can type what u want)
  web:
    build: .
    volumes:
      - .:/StudentsSystem
    ports:
      - "8030:8030"
    command: bash -c "
      ls &&
      python3 CodeSchoolAPI/manage.py makemigrations &&
      python3 CodeSchoolAPI/manage.py migrate &&
      python3 CodeSchoolAPI/manage.py runserver 0.0.0.0:8030"