services:
  #web is a service name (can type what u want)
  web:
    build: .
    volumes:
      - .:/CodeSchoolAPI
    ports:
      - "8000:8000"
      - "9200:9200"
    command: bash -c "
      ls &&
      cd StudentsSystem &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"