# Generated by Django 3.1.1 on 2020-09-21 17:50

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AddField(
            model_name='commentrelationship',
            name='liked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 17, 50, 12, 175393, tzinfo=utc)),
        ),
    ]
