# Generated by Django 3.1.1 on 2020-09-21 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('lecturer_name', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField()),
                ('duration', models.IntegerField(help_text='Enter number of hours')),
                ('slides_url', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('reacted_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_subscribed',
            field=models.ManyToManyField(through='lecture.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
