# Generated by Django 3.1.3 on 2020-11-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='lecture',
            name='admin_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='subscriber',
            field=models.ManyToManyField(related_name='subscriber', through='lecture.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
