# Generated by Django 2.2.15 on 2020-09-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20200904_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(help_text='Enter number of hours'),
        ),
    ]
