# Generated by Django 2.2.15 on 2020-09-07 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200905_0708'),
        ('lecture', '0004_auto_20200904_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
            ],
        ),
    ]
