# Generated by Django 2.2.15 on 2020-09-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='date',
            new_name='subdate',
        ),
    ]
