# Generated by Django 2.2.15 on 2020-09-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20200907_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
