# Generated by Django 2.2.15 on 2020-09-04 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Users',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileOfUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
