# Generated by Django 2.2.15 on 2020-09-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200904_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Users',
        ),
    ]
