# Generated by Django 2.2.15 on 2020-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb_profile',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=False, upload_to='profile-images'),
        ),
    ]
